#!/usr/bin/env python3
"""Generate the SnapFlip OG share card (1200x630 PNG) and embed it as base64
in src/web/og-image.ts so the Worker serves /og.png with zero dependencies.

Usage: python3 scripts/gen-og.py
Uses only stdlib + PIL. Re-run after changing the card copy below.
"""
import base64
import os
from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
BG = (7, 10, 8)
PHOS = (70, 255, 143)
DIM = (30, 122, 70)
AMBER = (255, 176, 0)
INK = (216, 236, 217)
MUTED = (127, 160, 138)
TAG_BG = (240, 226, 168)
TAG_INK = (28, 26, 20)

OUT_TS = os.path.join(os.path.dirname(__file__), "..", "src", "web", "og-image.ts")

CANDIDATE_FONTS = [
    "/System/Library/Fonts/Andale Mono.ttf",
    "/System/Library/Fonts/Supplemental/Andale Mono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]


def font(size: int):
    for path in CANDIDATE_FONTS:
        if os.path.exists(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def glow_text(draw: ImageDraw.ImageDraw, xy, text, fnt, color, glow):
    x, y = xy
    draw.text((x, y), text, font=fnt, fill=glow)
    # cheap phosphor bloom: dim copies around the glyph
    for dx, dy in ((2, 0), (-2, 0), (0, 2), (0, -2)):
        draw.text((x + dx, y + dy), text, font=fnt, fill=glow)
    draw.text((x, y), text, font=fnt, fill=color)


def main() -> None:
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)

    # scanlines + vignette frame
    for y in range(0, H, 4):
        d.line([(0, y), (W, y)], fill=(0, 0, 0))
    d.rectangle([8, 8, W - 9, H - 9], outline=DIM, width=3)

    f_small = font(44)
    f_mid = font(64)
    f_big = font(118)
    f_huge = font(190)

    glow_text(d, (70, 60), "snapflip", f_mid, PHOS, DIM)
    d.text((70, 150), "SOLD BEFORE", font=f_big, fill=INK)
    d.text((70, 290), "YOU BUY IT.", font=f_big, fill=INK)

    # price-tag motif: amber $6 tag -> SOLD $38
    d.rounded_rectangle([70, 470, 330, 560], radius=12, fill=TAG_BG)
    d.ellipse([92, 502, 112, 522], fill=BG)
    d.text((140, 478), "$6 tag", font=font(56), fill=TAG_INK)
    d.text((360, 478), "->", font=font(56), fill=MUTED)
    glow_text(d, (470, 460), "SOLD $38", font(72), AMBER, (106, 82, 0))

    d.text((860, 150), "60s clock", font=f_small, fill=PHOS)
    d.text((860, 220), "agents bid", font=f_small, fill=PHOS)
    d.text((860, 290), "10% fee*", font=f_small, fill=PHOS)
    d.text((860, 360), "*only when", font=font(32), fill=MUTED)
    d.text((860, 402), "it sells", font=font(32), fill=MUTED)
    d.text((70, 580), "go.snapflip.workers.dev", font=font(32), fill=MUTED)

    img.save("/tmp/snapflip-og.png")
    with open("/tmp/snapflip-og.png", "rb") as f:
        b64 = base64.b64encode(f.read()).decode()
    with open(OUT_TS, "w") as f:
        f.write(
            "// Auto-generated by scripts/gen-og.py — do not hand-edit. Re-run the script.\n"
            f"// 1200x630 OG share card, {len(b64) * 3 // 4} bytes PNG.\n"
            f'export const OG_PNG_BASE64 = "{b64}";\n'
        )
    print(f"og-image.ts written ({len(b64) // 1024} KB base64)")


if __name__ == "__main__":
    main()
